name: root_tester
description: A Flutter plugin to check if device is rooted or not.only for Android & iOS Devices.

version: 0.0.4
homepage: https://github.com/shashwatxx/root_tester

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:       
  plugin:
    platforms:
      android:
        package: me.shashwatmishra.root_tester
        pluginClass: RootTesterPlugin
      ios:
        pluginClass: RootTesterPlugin

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
